// Generated by CoffeeScript 1.3.3
(function() {
  var test;

  test = function(x, y) {
    if (y == null) {
      y = "Developer";
    }
    return "My Name is " + x(+"and I am a" + y);
  };

  console.log(test("iArivu"));

}).call(this);
